/* eslint-disable @next/next/no-img-element */
import React, { useEffect, useCallback, useState } from "react";
import { unescape } from "lodash";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { Header, Footer } from "../../components";
import { useRouter } from "next/router";

import { ACTION_TYPES } from "../../redux/actions/articleAction";

export default function Article() {
  const dispatch = useDispatch();
  const router = useRouter();
  const { id } = router.query;
  // Using the useSelector Hook to fetch the state from store.
  const fetchedCountries = useSelector((state) => state);

  const fetchedItem = useSelector(
    (state) => state?.articles?.item
  );
  const [buyCount, setBuyCount] = useState(1);

  function addThousandsSeparators(number) {
    return number.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
  }

  useEffect(() => {
    if (id) {
      dispatch({
        type: ACTION_TYPES.FETCH_ITEM,
        id,
      });
    }
  }, [id]);

  const handleAddToCart = useCallback(
    (item) => {
      const chartItem = {...item, count: buyCount};
      dispatch({
        type: ACTION_TYPES.ADD_CART,
        item: chartItem,
      });
      console.log(fetchedCountries);
    },
    [buyCount, dispatch, fetchedCountries]
  );

  return (
    <div>
      <Head>
        <title>IHGMA</title>
        <meta name="description" content="Generated by IHGMA" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <section className="bg-white pb-8 lg:px-36">
          <div className="container mx-auto flex items-center flex-wrap pt-4 pb-12 px-8 md:px-0">
            <section className="bg-white pt-4 pb-8 lg:px-36">
              <div className="flex flex-row px-6">
                <div className="basis-1/3">
                  <picture className="rounded-lg block overflow-hidden">
                    <img
                      className="object-cover w-full h-60"
                      src={"https://ihgma.org" + fetchedItem?.main_picture}
                    />
                  </picture>
                </div>
                <div className="basis-2/3 px-8 py-2">
                  <h1 className="text-2xl font-bold text-black">
                    {fetchedItem?.name}
                  </h1>
                  <p className="pt-3 text-gray-900">
                    {fetchedItem?.description}
                  </p>
                  <p className="pt-3 text-gray-900">IDR {addThousandsSeparators(fetchedItem?.price)}</p>
                  <div className="mt-4 flex rounded-lg text-lg" role="group">
                    <button
                      onClick={() => {
                        if (buyCount != 1) {
                          setBuyCount(buyCount - 1);
                        }
                      }}
                      className="bg-white text-slate-900 hover:bg-slate-900 hover:text-white border border-r-0 border-slate-900 rounded-l-lg px-4 py-2 mx-0 outline-none focus:shadow-outline"
                    >
                      -
                    </button>
                    <div className="bg-white text-slate-900 border border-slate-900  px-4 py-2 mx-0 outline-none focus:shadow-outline">
                      {buyCount}
                    </div>
                    <button
                      onClick={() => {
                        setBuyCount(buyCount + 1);
                      }}
                      className="bg-white text-slate-900 hover:bg-slate-900 hover:text-white border border-l-0 border-slate-900 rounded-r-lg px-4 py-2 mx-0 outline-none focus:shadow-outline"
                    >
                      +
                    </button>
                  </div>
                  <button
                    onClick={() => {
                      handleAddToCart(fetchedItem);
                    }}
                    className="mt-4 px-5 py-4 text-base font-medium text-center text-white transition duration-500 ease-in-out transform bg-blue-800 lg:px-10 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                  >
                    Add to Cart
                  </button>
                </div>
              </div>
            </section>
          </div>
        </section>
        <Footer />
      </main>
    </div>
  );
}
