/* eslint-disable @next/next/no-img-element */
import React, { useEffect, useState, useCallback } from "react";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { Header, Footer } from "../../components";
import { useRouter } from "next/router";

import { ACTION_TYPES } from "../../redux/actions/articleAction";

export default function Home() {
  const dispatch = useDispatch();
  const router = useRouter();
  // Using the useSelector Hook to fetch the state from store.
  const fetchedCountries = useSelector((state) => state);

  const fetchedVacancy = useSelector(
    (state) => state?.articles?.vacancyList
  );

  const [articleData, setArticleData] = useState([]);

  useEffect(() => {
    dispatch({
      type: ACTION_TYPES.FETCH_VACANCY,
    });
  }, [dispatch]);

  useEffect(() => {
    if (fetchedVacancy?.artikel) {
      setArticleData(fetchedVacancy?.artikel);
    }
  }, [fetchedVacancy?.artikel]);

  return (
    <div>
      <Head>
        <title>IHGMA</title>
        <meta name="description" content="Generated by IHGMA" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <section className="bg-white py-8 lg:px-36">
          <div className="container mx-auto flex items-center flex-wrap pt-4 pb-12">
            <nav id="store" className="w-full top-0 px-6 py-1 mb-6">
              <div className="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 px-2 pt-3">
                <div className="flex items-center gap-12">
                  <h2 className="text-2xl font-bold text-gray-800 lg:text-3xl">
                    Recent Post
                  </h2>
                </div>
              </div>
            </nav>

            <div className="grid grid-cols-1 gap-4 px-6 xl:grid-cols-3">
              {articleData &&
                articleData.map((c, index) => {
                  // const content = c.content;
                  // const unescapedHtml = unescape(content);
                  // const sanitizedHtml = unescapedHtml.replace(/\r?\n|\r/g, '');
                  // console.log(sanitizedHtml);
                  return (
                    <div
                      key={index}
                      className="w-full h-full p-2 flex flex-col"
                      onClick={() => router.push(`/vacancy/${c.id}`)}
                    >
                      <a className="h-full bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                          <img
                            className="object-cover w-full h-60"
                            src={c?.main_picture}
                          />
                        </picture>
                        <div className="px-5 pb-5">
                          <div className="mt-3 text-xs bg-blue-100 text-blue-800  py-1 px-3 w-min">
                            {c.category}
                          </div>
                          <div className="pt-2 flex items-center justify-between">
                            <p className="text-2xl text-slate-900 font-semibold">
                              {c.title}
                            </p>
                          </div>
                          <p className="text-lg pt-2 text-blue-800 font-medium">
                            Read More
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              fill="none"
                              viewBox="0 0 24 24"
                              strokeWidth="1.5"
                              stroke="currentColor"
                              className="w-6 h-6 inline"
                            >
                              <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                d="M17.25 8.25L21 12m0 0l-3.75 3.75M21 12H3"
                              />
                            </svg>
                          </p>
                        </div>
                        <div className="absolute bottom-0 h-[5px] w-1/6 bg-gradient-to-r from-[#7b3a94] via-[#332f5b] to-[#1b8393] ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                      </a>
                    </div>
                  );
                })}
            </div>
          </div>
        </section>

        <div className="bg-white py-6 sm:py-8 lg:py-12">
          <div className="mx-auto max-w-screen-2xl px-4 md:px-8">
            <div className="flex flex-col items-center justify-between gap-4  bg-gray-100 p-4 sm:flex-row md:p-8">
              <div>
                <h2 className="text-xl font-bold text-blue-800 md:text-2xl">
                  Become A Member
                </h2>
                <p className="text-gray-600">Start Your Journey Now!</p>
              </div>

              <a
                href="#"
                className="inline-block bg-blue-800 px-8 py-3 text-center text-sm font-semibold text-white outline-none ring-indigo-300 transition duration-100 hover:bg-blue-600 focus-visible:ring active:bg-blue-700 md:text-base"
              >
                Register
              </a>
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </div>
  );
}
