/* eslint-disable @next/next/no-img-element */
import React, { useEffect, useCallback, useState } from "react";
import { unescape } from "lodash";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { Header, Footer } from "../../components";
import { useRouter } from "next/router";

import { ACTION_TYPES } from "../../redux/actions/articleAction";

export default function Article() {
  const dispatch = useDispatch();
  const router = useRouter();

  const upgradeResponse = useSelector(
    (state) => state?.articles?.upgradeResponse
  );
  const dpdList = useSelector((state) => state?.articles?.dpd?.dpd);
  const user = useSelector((state) => state?.articles?.user);

  const [values, setValues] = useState({
    id: "",
    hotel: "",
    hotel_add: "",
    dpd: "",
  });

  const handleInputChange = (event) => {
    const { name, value } = event.target;
    if (name == "birthdate") {
      const selectedDate = new Date(value);
      const year = selectedDate.getFullYear();
      const month = String(selectedDate.getMonth() + 1).padStart(2, "0");
      const day = String(selectedDate.getDate()).padStart(2, "0");
      const formattedDate = `${year}-${month}-${day}`;
    }
    setValues((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  useEffect(() => {
    dispatch({
      type: ACTION_TYPES.FETCH_DPD,
    });
  }, [dispatch]);
  useEffect(() => {
    console.log(values);
  }, [values]);

  useEffect(() => {
    dispatch({
      type: ACTION_TYPES.UPGRADE_CLEAR,
    });
  }, []);

  function handleSubmit(event) {
    event.preventDefault();
    const params = { values, uid: user.uid };
    dispatch({
      type: ACTION_TYPES.UPGRADE,
      params,
    });
  }

  return (
    <div>
      <Head>
        <title>IHGMA</title>
        <meta name="description" content="Generated by IHGMA" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section className="bg-white py-8 lg:px-36 px-4">
        <form
          onSubmit={handleSubmit}
          className="bg-white border border-gray-200 rounded-lg shadow p-4"
        >
          <p className="mb-4 font-semibold">New Member Form</p>
          <div className="mb-6">
            <label
              // for="name"
              className="block mb-2 text-sm font-medium text-gray-900"
            >
              Full Name
            </label>
            <input
              type="name"
              id="name"
              name="name"
              className="bg-gray-200 border border-gray-500 text-gray-500 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
              placeholder="John Doe"
              value={user.name}
              onChange={handleInputChange}
              disabled
              required
            ></input>
          </div>
          <div className="mb-6">
            <label
              // for="email"
              className="block mb-2 text-sm font-medium text-gray-900"
            >
              Birthdate
            </label>
            <input
              type="date"
              id="birthdate"
              name="birthdate"
              value={user.birthdate}
              onChange={handleInputChange}
              className="border rounded bg-gray-200 text-gray-500 px-2 py-1"
              disabled
            />
          </div>
          <div className="mb-6">
            <label
              // for="email"
              className="block mb-2 text-sm font-medium text-gray-900"
            >
              ID KTP / SIM
            </label>
            <input
              type="number"
              id="id"
              name="id"
              className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
              placeholder="masukan nomor KTP / SIM"
              value={values.id}
              onChange={handleInputChange}
              required
            ></input>
          </div>
          <div className="mb-6">
            <label
              // for="email"
              className="block mb-2 text-sm font-medium text-gray-900"
            >
              Home Address
            </label>
            <input
              type="text"
              id="address"
              name="address"
              className="bg-gray-200 border border-gray-500 text-gray-500 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
              placeholder="Jalan Mawar no 31, Jakarta Barat"
              value={user.home_address}
              onChange={handleInputChange}
              required
              disabled
            ></input>
          </div>
          <div className="mb-6">
            <label
              // for="email"
              className="block mb-2 text-sm font-medium text-gray-900"
            >
              Phone Number
            </label>
            <input
              type="tel"
              pattern="^\d{9,13}$"
              id="phone"
              name="phone"
              className="bg-gray-200 border border-gray-500 text-gray-500 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
              placeholder="Phone number (123-456-7890)"
              value={user.phone}
              onChange={handleInputChange}
              required
              disabled
            ></input>
          </div>
          <div className="mb-6">
            <label
              // for="email"
              className="block mb-2 text-sm font-medium text-gray-900"
            >
              Email
            </label>
            <input
              type="email"
              id="email"
              name="email"
              className="bg-gray-200 border border-gray-500 text-gray-500 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
              placeholder="name@example.com"
              value={user.email}
              onChange={handleInputChange}
              required
              disabled
            ></input>
          </div>
          <div className="mb-6">
            <label
              // for="email"
              className="block mb-2 text-sm font-medium text-gray-900"
            >
              Current Hotel
            </label>
            <input
              type="text"
              id="hotel"
              name="hotel"
              className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
              placeholder="Masukan Nama Hotel"
              value={values.hotel}
              onChange={handleInputChange}
              required
            ></input>
          </div>
          <div className="mb-6">
            <label
              // for="email"
              className="block mb-2 text-sm font-medium text-gray-900"
            >
              Hotel Address
            </label>
            <input
              type="text"
              id="hotel_add"
              name="hotel_add"
              className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
              placeholder="Masukan Alamat Hotel"
              value={values.hotel_add}
              onChange={handleInputChange}
              required
            ></input>
          </div>
          <div className="mb-6">
            <label
              // for="email"
              className="block mb-2 text-sm font-medium text-gray-900"
            >
              DPD (Dewan Pimpinan Daerah)
            </label>
            <select className="rounded-lg" name="dpd" id="dpd" onChange={handleInputChange} required>
              {dpdList?.map((dpd, index) => (
                <option key={index} value={dpd?.code}>
                  {dpd?.region}
                </option>
              ))}
            </select>
          </div>
          <div className="mb-6">
            <label
              // for="name"
              className="block mb-2 text-sm font-medium text-gray-900"
            >
              Username
            </label>
            <input
              type="name"
              id="username"
              name="username"
              className="bg-gray-200 border border-gray-500 text-gray-500 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
              placeholder="JohnDoe123"
              title="Jangan menggunakan spasi maupun karakter spesial"
              pattern="^[a-zA-Z0-9]*$"
              value={user.username}
              onChange={handleInputChange}
              required
              disabled
            ></input>
          </div>
          {upgradeResponse?.data?.status == "error" && (
            <p className="text-base text-red-600 font-bold mb-4 ml-2">
              ERROR: {upgradeResponse?.data?.msg}
            </p>
          )}
          {upgradeResponse?.data?.status == "success" && (
            <p className="text-base text-green-600 font-bold mb-4 ml-2">
              Pendaftaran berhasil, Silahkan tunggu konfirmasi dari admin
            </p>
          )}
          <button
            type="submit"
            // onClick={handleSubmit}
            className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center"
          >
            Register
          </button>
        </form>
      </section>
      <Footer />
    </div>
  );
}
