import styles from "../styles/Home.module.css";
import React from "react";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";

import { ACTION_TYPES } from "../redux/actions/articleAction";

export default function Home() {
  const dispatch = useDispatch(); 
  // Using the useSelector Hook to fetch the state from store.
  const fetchedCountries = useSelector((state) => state?.articles?.articleHomeList);

  React.useEffect(() => {
    dispatch({
      type: ACTION_TYPES.FETCH_ARTICLE_HOME,
    });
    console.log(fetchedCountries);
  }, [dispatch, fetchedCountries]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>All Countries</h1>
        <p className="pt-3 text-gray-900 text-sm">IDR 50.000</p>
        {/* {fetchedCountries && fetchedCountries?.map((c) => (
          <h3 className="pt-4" key={c.name.common}>{c.name.common}</h3>
        ))} */}
      </main>
    </div>
  );
}
