/* eslint-disable @next/next/no-img-element */
import styles from "../styles/Home.module.css";
import React from "react";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";

import { useRouter } from "next/router";

export default function Home() {
  const dispatch = useDispatch();
  const router = useRouter();
  // Using the useSelector Hook to fetch the state from store.
  const fetchedCountries = useSelector(
    (state) => state?.articles
  );

  React.useEffect(() => {
    const timeoutId = setTimeout(() => {
      router.push("/home");
    }, 500);

    // Clean up the timeout when the component unmounts or when the effect is re-run
    return () => clearTimeout(timeoutId);
  }, [router]);

  return (
    <div>
      <Head>
        <title>IHGMA</title>
        <meta name="description" content="Generated by IHGMA" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="https://i.gifer.com/ZNeT.gif" width={100} height={100} alt="loader"></img>
      </main>
    </div>
  );
}
