/* eslint-disable @next/next/no-img-element */
import React, { useEffect, useCallback, useState } from "react";
import { unescape } from "lodash";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { Header, Footer } from "../../components";
import { useRouter } from "next/router";

import { ACTION_TYPES } from "../../redux/actions/articleAction";
import userRole from "../../libs/constant";

export default function Article() {
  const dispatch = useDispatch();
  const router = useRouter();
  // Using the useSelector Hook to fetch the state from store.
  const user = useSelector((state) => state?.articles?.user);

  const handleUpdateCount = useCallback(
    (index, count) => {
      dispatch({
        type: ACTION_TYPES.UPDATE_COUNT,
        payload: { index, count },
      });
    },
    [dispatch]
  );

  const handleDeleteItem = useCallback(
    (index) => {
      dispatch({
        type: ACTION_TYPES.DELETE_ITEM,
        payload: index,
      });
    },
    [dispatch]
  );

  return (
    <div>
      <Head>
        <title>IHGMA</title>
        <meta name="description" content="Generated by IHGMA" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <section className="bg-white py-8 lg:px-36">
          <div className="container mx-auto flex items-center flex-wrap px-4">
            {user?.role == userRole.User ||
            user?.role == userRole.UserNonaktif ? (
              <p>You are not allowed to access AD/ART File</p>
            ) : (
              <object
                data="https://ihgma.org/assets/adart.pdf"
                width="100%"
                className="h-[400px] md:h-[800px]"
              >
                <p>Oops! Your browser doesn&apos;t support PDFs!</p>
                <p>
                  <a href="https://ihgma.org/assets/adart.pdf">
                    Download Instead
                  </a>
                </p>
              </object>
            )}
          </div>
        </section>
        <Footer />
      </main>
    </div>
  );
}
