/* eslint-disable @next/next/no-img-element */
import React, { useEffect, useCallback, useState } from "react";
import { unescape } from "lodash";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { Header, Footer } from "../../components";
import { useRouter } from "next/router";

import { ACTION_TYPES } from "../../redux/actions/articleAction";
import userRole from "../../libs/constant";

export default function Structure() {
  const dispatch = useDispatch();
  const router = useRouter();
  // Using the useSelector Hook to fetch the state from store.
  const user = useSelector((state) => state?.articles?.user);

  const handleUpdateCount = useCallback(
    (index, count) => {
      dispatch({
        type: ACTION_TYPES.UPDATE_COUNT,
        payload: { index, count },
      });
    },
    [dispatch]
  );

  return (
    <div>
      <Head>
        <title>IHGMA</title>
        <meta name="description" content="Generated by IHGMA" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <section className="bg-white py-8 lg:px-36">
        <div className="container mx-auto flex items-center flex-wrap pb-12">

            <nav id="store" className="w-full top-0 px-6 py-1">
                <div className="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 px-2 pb-3">

                <a className="tracking-wide no-underline hover:no-underline text-3xl font-semibold text-blue-800 mb-4">
				    Organizational Structure
			    </a>
                <p className="mb-2">Susunan Pengurus DPP IHGMA Periode 2021 – 2024 yang ditunjuk oleh Presiden IHGMA berdasarkan amanat Kongres ke 2 IHGMA di Sumatera Utara adalah sebagai berikut:</p>
              </div>
            </nav>

            <div data-modal-target="defaultModal" data-modal-toggle="defaultModal" className="grid grid-cols-1 gap-4 px-6 xl:grid-cols-4 w-full">
                <div className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <img className="object-cover w-full h-80 hover:grow" src="https://ihgma.org/assets/pengurus6.jpg" />
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Dr. I Gede Arya Pering Arimbawa, SE, Msi, CHA</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Presiden</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>

                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <img className="object-cover w-full h-80 hover:grow" src="https://ihgma.org/assets/alihidayat.jpg" />
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Ali Hidayat</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Wakil Presiden 1</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Wita Junifah</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Wakil Presiden 2</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <img className="object-cover w-full h-80 hover:grow" src="https://ihgma.org/assets/BustamarKoto.jpg" />
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Bustamar Koto ST.Par</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Sekretaris Jendral</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <img className="object-cover w-full h-80 hover:grow" src="https://ihgma.org/assets/NawawiHalik.png" />
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Nawawi Halik</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Wakil Sekjen 1</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Achmad Zulham, CHA</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Wakil Sekjen 2</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Herryadi Baiin</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Wakil Sekjen 3</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Achmad Ridwan Deskana SE, Ak, MM, CHA</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Bendahara Umum</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Zulkifli Noor</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Wakil Bendahara</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
           </div>
           <a className="tracking-wide no-underline hover:no-underline text-2xl font-semibold text-blue-800 mb-4 px-6 my-8">
                BIDANG PELATIHAN, AKREDITASI & SERTIFIKASI
            </a>
            <div data-modal-target="defaultModal" data-modal-toggle="defaultModal" className="grid grid-cols-1 gap-4 px-6 xl:grid-cols-4 w-full">
                <div className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Braja Eka Sukma, ST.Par, CHA</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Ketua</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>

                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <img className="object-cover w-full h-80 hover:grow" src="https://ihgma.org/assets/EkaGartika.jpg" />
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Eka Gartika</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Wakil Ketua</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <img className="object-cover w-full h-80 hover:grow" src="https://ihgma.org/assets/FreddyPantouw.jpg" />
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Freddy Pantouw, CMTH, CHT</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Riswan Surbakti</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Syahrul Sauta, MM, D.B.A, CHA, CHGMA</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
            </div>
            <a className="tracking-wide no-underline hover:no-underline text-2xl font-semibold text-blue-800 mb-4 px-6 my-8">
                BIDANG ORGANISASI
            </a>
            <div data-modal-target="defaultModal" data-modal-toggle="defaultModal" className="grid grid-cols-1 gap-4 px-6 xl:grid-cols-4 w-full">
                <div className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <img className="object-cover w-full h-80 hover:grow" src="https://ihgma.org/assets/JokoWidiyanto.jpg" />
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Joko S. Widyanto</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Ketua</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>

                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <img className="object-cover w-full h-80 hover:grow" src="https://ihgma.org/assets/JimanBudiharja.jpg" />
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Jiman Budiharja, CHA</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Wakil Ketua</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <img className="object-cover w-full h-80 hover:grow" src="https://ihgma.org/assets/SugengSugiantoro.jpg" />
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Sugeng Sugiantoro</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Ernanda D. Agung, CHA</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
            </div>
            <a className="tracking-wide no-underline hover:no-underline text-2xl font-semibold text-blue-800 mb-4 px-6 my-8">
                BIDANG HUMAS & PEMASARAN
            </a>
            <div data-modal-target="defaultModal" data-modal-toggle="defaultModal" className="grid grid-cols-1 gap-4 px-6 xl:grid-cols-4 w-full">
                <div className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Cita Hepiningtias</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Ketua</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Alan Muhammad Yuslan</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <img className="object-cover w-full h-80 hover:grow" src="https://ihgma.org/assets/TeddyPatrick.jpeg" />
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Teddy Patrick, SE, M.Par, CHA</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
            </div>
            <a className="tracking-wide no-underline hover:no-underline text-2xl font-semibold text-blue-800 mb-4 px-6 my-8">
                BIDANG LITBANG & INFORMASI TEKNOLOGI
            </a>
            <div data-modal-target="defaultModal" data-modal-toggle="defaultModal" className="grid grid-cols-1 gap-4 px-6 xl:grid-cols-4 w-full">
                <div className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Agus Juharto</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Ketua</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>

                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <img className="object-cover w-full h-80 hover:grow" src="https://ihgma.org/assets/YeyenHeryawan.jpeg" />
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Yeyen Heryawan</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Wakil Ketua</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Joko Budi Jaya, SE</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Hartini Mochtar</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
            </div>
            <a className="tracking-wide no-underline hover:no-underline text-2xl font-semibold text-blue-800 mb-4 px-6 my-8">
                BIDANG KEANGGOTAAN
            </a>
            <div data-modal-target="defaultModal" data-modal-toggle="defaultModal" className="grid grid-cols-1 gap-4 px-6 xl:grid-cols-4 w-full">
                <div className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Doddy Fathurahman</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Ketua</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>

                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Chandra Hadi</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Wakil Ketua</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <img className="object-cover w-full h-80 hover:grow" src="https://ihgma.org/assets/Sumargo.jpeg" />
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Sumargo, SE, CHM</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Iskandar Erlangga</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <img className="object-cover w-full h-80 hover:grow" src="https://ihgma.org/assets/BobiSetiaBudi.jpeg" />
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Bobi Setiabudi</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
            </div>
            <a className="tracking-wide no-underline hover:no-underline text-2xl font-semibold text-blue-800 mb-4 px-6 my-8">
                BIDANG UMUM KELEMBAGAAN, PERIZINAN & LEGAL
            </a>
            <div data-modal-target="defaultModal" data-modal-toggle="defaultModal" className="grid grid-cols-1 gap-4 px-6 xl:grid-cols-4 w-full">
                <div className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <img className="object-cover w-full h-80 hover:grow" src="https://ihgma.org/assets/Rondan.jpeg" />
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Rondan Sukarnadi</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Ketua</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>

                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Anton Gemilar</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Wakil Ketua</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <img className="object-cover w-full h-80 hover:grow" src="https://ihgma.org/assets/MahmudAlhabsyi.jpg" />
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Mahmud Al Habsy</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Muhammad Zakaria</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
            </div>
            <a className="tracking-wide no-underline hover:no-underline text-2xl font-semibold text-blue-800 mb-4 px-6 my-8">
                BIDANG EVENT & CSR
            </a>
            <div data-modal-target="defaultModal" data-modal-toggle="defaultModal" className="grid grid-cols-1 gap-4 px-6 xl:grid-cols-4 w-full">
                <div className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">I Gusti Bagus Agung Suddhajinendra HS. SST.Par</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Ketua</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>

                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">M Harun Al Rasjid</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Wakil Ketua</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Bregas Yekti</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            <img className="object-cover w-full h-80 hover:grow" src="https://ihgma.org/assets/AgusSuyatna.jpg" />
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Agus Suyatna</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
                <div  className="w-full p-2 flex flex-col">
                    <a className="bg-white drop-shadow-lg hover:shadow-lg group">
                        <picture className="block overflow-hidden">
                            
                            <div className="w-full h-80 bg-gray-200"></div>
                        </picture>
                        <div className="px-[20px] pb-5 h-40">
                            <div className="pt-4 flex items-center justify-between">
                                <p className="text-xl text-slate-900 font-semibold">Wied Paramartha</p>
                            </div>
                            <p className="text-lg pt-2 text-blue-800 font-medium">Anggota</p>
                        </div>
                        <div className="h-[5px] w-1/6 bg-blue-800 ease-out duration-300 group-hover:w-full group-hover:transition-all"></div>
                    </a>
                </div>
            </div>
        </div>
    </section>
        <Footer />
      </main>
    </div>
  );
}
